### ISSUE TITLE
Cannot compile on raspberry pi 4B due to sh: 1: ./ptr_size_generator: Exec format error

### ISSUE THREAD

**Issue by mormyrid1** [picoruby/picoruby#106]
**Describe the bug**
PicoRuby cannot be compiled on anything other than x86-64 due to the ptr_size_generator executable in mruby-pico-compiler

**To Reproduce**
Run rake on a non x86-64 architecture

sh: 1: ./ptr_size_generator: Exec format error
rake aborted!

**To Fix**
simply delete picoruby/mrbgems/mruby-pico-compiler/lib/ptr_size_generator and recompile before running rake in picoruby/

This is all that is needed to get picoruby working on Linux raspberrypi 5.15.32-v7l+ #1538 SMP Thu Mar 31 19:39:41 BST 2022 armv7l GNU/Linux

**Additional context**
Perhaps rake can compile a test program to determine the pointer length, like configure does, to avaoid having to have a pre compiled binary. Or just pre generate the header file with known values.

**Comment by hasumikin** [comment]
@mormyrid1 Thanks for the report. I think I could fix it
