### ISSUE TITLE
ruby scripts that use sleep fail

### ISSUE THREAD

**Issue by mormyrid1** [picoruby/picoruby#109]
While trying to get the mruby sample_include.c example working in picoruby it fails with `munmap_chunk(): invalid pointer`
![Screenshot_2022-05-08_14-40-56](https://user-images.githubusercontent.com/61082507/167298946-9023584e-acd4-4c62-b5b9-8eefc600c5cd.png)

the ruby script is

```
while true
  puts 'sample'
  sleep 1
end
```

It also does not work wben compiled into firmware. This was converted to bytecode with `picorbc -Bary hello.rb` and then loaded in main.c

```/**
 * Copyright (c) 2020 Raspberry Pi (Trading) Ltd.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include <stdio.h>
#include "pico/stdlib.h"
#include "mrubyc.h"

#include "hello.c"

#define MEMORY_SIZE (1024*40)
static uint8_t memory_pool[MEMORY_SIZE];

int main() {
  stdio_init_all();
  mrbc_init(memory_pool, MEMORY_SIZE);

  if( mrbc_create_task(ary, 0) != NULL ){
    mrbc_run();
  }

  return 0;
}
```

if i remove the sleep statement it works as expected.

Compiled on  Linux raspberrypi 5.15.32-v7l+ #1538 SMP Thu Mar 31 19:39:41 BST 2022 armv7l GNU/Linux

**Comment by hasumikin** [comment]
@mormyrid1 
PicoRuby, mruby/c to be exact, uses a special mechanism which is a concept of "task" to realize `sleep()`.
bin/picoruby doesn't create any task so `sleep()` naturally doesn't work.
See https://github.com/mrubyc/mrubyc/blob/master/sample_c/sample_scheduler.c#L45 to know how to create a task
