### ISSUE TITLE
How to install picoruby globally?

### ISSUE THREAD

**Issue by postmodern** [picoruby/picoruby#130]
I would like to add support for installing picoruby to [ruby-install](https://github.com/postmodern/ruby-install/issues/433). In order to do this, I need to be able to install `picoruby` into either `/usr/local/` (and comply with the [Filesystem Hierarchy Standard](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html)), or `/opt/rubies/picoruby-3.0.2/`, or `~/.rubies/picoruby-3.0.2/`. There doesn't seem to be any documentation on how to install picoruby outside of the repo, but it seems like it could be possible to copy the `bin/pico*` binaries into a `bin/` directory, or copy the `lib/` directory into a `$(PREFIX)/share/picoruby/` directory.

**Comment by hasumikin** [comment]
@postmodern 
You can install picoruby through rbenv:

![image](https://user-images.githubusercontent.com/8454208/217680238-fe2bcae7-84d2-491e-a31b-ac5706226485.png)

Does this help you?

**Comment by postmodern** [comment]
@hasumikin not exactly. Instead of just wanting to install picoruby, I am the maintainer of [ruby-install]() and am interested in adding support for [installing picoruby to ruby-install](https://github.com/postmodern/ruby-install/issues/433).

**Comment by hasumikin** [comment]
@postmodern 
Ah, I see.

>but it seems like it could be possible to copy the bin/pico* binaries into a bin/ directory

I think this works

**Comment by hasumikin** [comment]
Will close this issue unless any comment post in a week
